"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _category_card from './category-card.bones.json'
import _product_card from './product-card.bones.json'

registerBones({
  "category-card": _category_card,
  "product-card": _product_card,
})
